### ISSUE TITLE
ggplot - plant phys csv

### ISSUE THREAD

**Issue by sstevens2** [uw-madison-comps/R-plant-lesson#15]
In [ggplot lesson](https://uw-madison-comps.github.io/R-plant-lesson/04-visualization-ggplot2/index.html):
```
plant_phys<-read_csv("data_output/phys_dates.csv")
```
The `data_output` folder referenced above is not listed there. 
Is the file `data/Physiology_Environmental_Data.csv` the file needed there?

@kimokeefe maybe you know?

**Comment by sstevens2** [comment]
If this is the right file... when I read it into R I got this warning about an extra column with no header row.
```r
> plant_phys<-read_csv(paste(path2data,"Physiology_Environmental_Data.csv", sep="/"))
Parsed with column specification:
cols(
  Year = col_double(),
  DOY = col_double(),
  Species = col_character(),
  Fgroup = col_character(),
  Cond_night = col_double(),
  Trmmol_night = col_double(),
  Photo = col_double(),
  Cond_day = col_double(),
  Trmmol_day = col_double(),
  Percent_cond = col_double(),
  Percent_trmmol = col_double(),
  PD = col_double(),
  MD = col_double(),
  Soil_moisture = col_double(),
  TAIR_N = col_double(),
  VPD_N = col_double(),
  TAIR_D = col_double(),
  VPD_D = col_double(),
  X19 = col_logical()
)
Warning message:
Missing column names filled in: 'X19' [19] 
```

**Comment by sstevens2** [comment]
Based on some info from @maglet and @SteveGoldstein, I found the `data` and `data_output` folders in the `_episodes_rmd` folder.  Maybe we should link these to the main repo's `data` folder?

**Comment by sstevens2** [comment]
@maglet I think this is just confusion about the two `data` folders for the most part.  Might be solved by #17?

**Comment by kimokeefe** [comment]
I'm not entirely sure, but it seems like the phys_dates.csv file was created by Tobin in the first lesson, and that's the file that they would like to work with in the second lesson - so it should be in the data_output folder. I don't care if there's one folder for both the original data and output data, or if you separate them.

I removed the extra empty column in the original Physiology_Environmental.csv data file and uploaded that new version to the data folder.

**Comment by maglet** [comment]
This seems to be working now as well.
