### ISSUE TITLE
ggplot - Column header typo

### ISSUE THREAD

**Issue by sstevens2** [uw-madison-comps/R-plant-lesson#18]
@maglet 
In [ggplot lesson](https://uw-madison-comps.github.io/R-plant-lesson/04-visualization-ggplot2/index.html):
```r
ggplot(data = iris, 
       mapping = aes(x = sepal.length, 
                     y = sepal.width))
```
`sepal.length` -> `sepal_length`
`sepal.width` -> `sepal_width`

Seems to be right in subsequent usages.

**Comment by maglet** [comment]
Thanks for pointing this out. We're actually going to change them all to Sepal.Length format to go along with the original iris dataset format.
