### ISSUE TITLE
ggplot - plots not showing in lessons

### ISSUE THREAD

**Issue by sstevens2** [uw-madison-comps/R-plant-lesson#19]
@maglet 

In [ggplot lesson](https://uw-madison-comps.github.io/R-plant-lesson/04-visualization-ggplot2/index.html):
There seem to be many broken image links in this section.  Not urgent for teaching but we may want to fix it at some point

**Comment by maglet** [comment]
I added back in the source(chunk_options.R) file back in and it fixed the file paths.
