### ISSUE TITLE
ggplot - challenge error message

### ISSUE THREAD

**Issue by sstevens2** [uw-madison-comps/R-plant-lesson#20]
@maglet 
In [ggplot lesson](https://uw-madison-comps.github.io/R-plant-lesson/04-visualization-ggplot2/index.html):
In *ggplot2 themes* section challenge has error showing. Which seems to be something to do with a `'` single quote.

```r
## Error: <text>:12:5: unexpected symbol
## 11: 
## 12: The `facet_wrap`
##         ^
```

**Comment by sstevens2** [comment]
Also error further up in *building plots interactively* section:

```r
## Error in FUN(X[[i]], ...): object 'species' not found
```

**Comment by maglet** [comment]
Thanks! i forgot the closing ```
