### ISSUE TITLE
Challenges template incompatibility 

### ISSUE THREAD

**Issue by sstevens2** [uw-madison-comps/R-plant-lesson#21]
@maglet 
Challenges are rendering strangely.  Seems like it might be the difference between old ecology template and new lessons template?

**Comment by maglet** [comment]
Here's the syntax from a SWC challenge: 

\> ## Challenge 1
\>
\> Write a single command (which can span multiple lines and includes pipes) that
\> will produce a dataframe that has the African values for `lifeExp`, `country`
\> and `year`, but not for other Continents.  How many rows does your dataframe
\> have and why?
\>
\> > ## Solution to Challenge 1
\> >```{r}
\> >year_country_lifeExp_Africa <- gapminder %>%
\> >                            filter(continent == "Africa") %>%
\> >                            select(year, country, lifeExp)
\> > ```
\> {: .solution}
\{: .challenge}

**Comment by maglet** [comment]
anyone know how to make the above not render ?

**Comment by sstevens2** [comment]
Apparently I can update your comments?  That seems creepy...but I put `\` in front of each line in the block to stop it from rendering.

**Comment by maglet** [comment]
That is creepy! But i can confirm that this syntax renders properly

**Comment by maglet** [comment]
I fixed the challenges for the ggplot2 lesson as well.

**Comment by maglet** [comment]
I fixed this in @SteveGoldstein 's lessons as well. we should be good.
