### ISSUE TITLE
edit dplyr mutate challenge: 

### ISSUE THREAD

**Issue by maglet** [uw-madison-comps/R-plant-lesson#24]
From kim: 
If it's okay with everyone, I think I'm going to have the students start off the advanced lesson by graphing the relationships of the nighttime physiological variables (transpiration / conductance) with various environmental and daytime physiological parameters (as a lead-up to the analyses). If so, can you avoid making that one of the challenges in the earlier lessons?

**Comment by maglet** [comment]
@kimokeefe do you have any suggestions for what to use for a challenge here? I can definitely make something up, but i'd like it to be a little biologically relevant.

**Comment by kimokeefe** [comment]
Hm, if you'd like a challenge for mutate, I'd suggest maybe using some of the data to calculate a new physiological parameter. For instance, you can calculate Instantaneous Water-Use Efficiency (WUE) by dividing photosynthesis by transpiration, and create a new column for that. 

WUE is basically an efficiency measure of how much carbon is gained by photosynthesis per water lost through transpiration - plants would ideally want to lose less water per carbon gained (= higher WUE), and often times there is a difference among species / functional groups (grasses typically have a high WUE). It would be fun to calculate this and then maybe graph the results by species or by functional type?

**Comment by maglet** [comment]
This sounds great! THank you for the suggestion. I'll work on this in the afternoon

**Comment by kimokeefe** [comment]
Awesome! No problem - let me know if you need any other suggestions.
