### ISSUE TITLE
fig dir is not populated

### ISSUE THREAD

**Issue by SteveGoldstein** [uw-madison-comps/R-plant-lesson#33]
In Lesson 00-before-we-start.Rmd, there several figures referenced to the fig/ subdirectories. That directory isn't populated, but the top level fig/ dir is and has the *.png files.  Should these be copied or moved to _episodes_rmd/fig/?  Or is there something automatic that ought to happen but is not?

**Comment by maglet** [comment]
The working directory for the github pages is in the main folder, not the RMD folder, so the file path should work? I'm not sure why it isn't finding the files. @sstevens2 any thoughts?

**Comment by SteveGoldstein** [comment]
I'm having a similar issue adding @kimokeefe advanced lesson.  `make serve` (or maybe it's `jekyll`) generates figures`figure/unnamed-chunk-2-1.png` and `figure/unnamed-chunk-3-1.png` but they are not found in the html files.

**Comment by maglet** [comment]
I figured it out: you need a setup block that sets the directory for figures. I fixed it in Kim's lessons. Here's what it looks like. I usually load packages and data behind the scenes to help the lessons render. 

```{r setup, message = FALSE, warning = FALSE, echo = FALSE}
library(tidyverse)
library(arm)
library(MuMIn)

source("../bin/chunk-options.R")
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
knitr_fig_path("05-")

phys_data<-read.csv("data/Physiology_Environmental_Data.csv")
```

**Comment by maglet** [comment]
For lesson 01, i changed the file path of the images to "../fig" and it seems to render now
