### ISSUE TITLE
Dots in object names

### ISSUE THREAD

**Issue by SteveGoldstein** [uw-madison-comps/R-plant-lesson#36]
In Lesson 01, it says:

> It’s also best to avoid dots (.) within an object name as in my.dataset. There are many functions in R with dots in their names for historical reasons, but because dots have a special meaning in R (for methods) and other programming languages, it’s best to avoid them. 

But the column names in the iris dataset have dots and so the use of dots is ubiquitous.  Can we just delete this text?

(Also:  I don't totally agree with this opinion.)

**Comment by maglet** [comment]
the object is called iris, and doesn't havea . dot. It doesn't say anything about variable/column names. 

But i'm also fine with deleting it if you want.

**Comment by SteveGoldstein** [comment]
Now I see the distinction.  Let's leave the sentence in.
