### ISSUE TITLE
Episode 2 suggestions

### ISSUE THREAD

**Issue by kathrynmichel** [uw-madison-comps/R-plant-lesson#45]
@SteveGoldstein 

Can we include images in the R markdown files? I like this one for showing the petals and sepals of the different species: 
![image](https://user-images.githubusercontent.com/29780361/64346053-0e74a100-cfb7-11e9-9fbc-d47d025085fd.png)

Line 40: Should we just keep the first workshop to the iris data to minimize confusion, and since none of the exercises need more complex data?
Line 41: "Each row holds information for an individual plant observation"

Line 57: This URL should work for downloading the data: "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
**EDIT:** the current link isn't for the iris data, update to use the correct link from our data folder

Please see the attached txt file
[factorEdits.txt](https://github.com/uw-madison-comps/R-plant-lesson/files/3580124/factorEdits.txt)
 with the edits for replacing sex as a factor. 

Line 348: Number of observations by species, not sex. 
Yes, I think lines 356-388 can be skipped, we may be getting short on time for this session.

**Comment by kathrynmichel** [comment]
I'm seeing now I didn't 100% understand the data folder here on github, so you can ignore my comments about which folders to use on local machines.

**Comment by maglet** [comment]
I really like the idea of including images. The ones you suggest are great!

**Comment by SteveGoldstein** [comment]
Beautiful images!
I'll incorporate your changes before our 9 AM meeting on Monday.

**Comment by SteveGoldstein** [comment]
I incorporated all these in PR #61
