### ISSUE TITLE
dplyr episode suggestions

### ISSUE THREAD

**Issue by kathrynmichel** [uw-madison-comps/R-plant-lesson#46]
1. Read in the iris dataset at the beginning, since it is a new workshop day
2. The column names in the data/iris.csv file don't match how they're referred to in the lesson.

In the Rmd file for this lesson:
Line 201: "observations", not "animals" 
Line 217: create a "ratio of sepal length to sepal width", not "weight in kg".
Line 227: need to add "iris %>%" to the front of the mutate statement
Line 230: The "#" didn't comment this line out in the rendered page
Lines 238 & 248: the columns you tell them to use in 238 don't match the commands in 248
Line 255: This line is not rendering as a header in the webpage

install.packages("lubridate") throws an error on the rendered page

Line 270: Can you use a day other than Jan 1? Maybe 15 or something so both the month and day aren't the same number?
Line 280: Do we need to explain here why we need the assignment operator when the name of the tibble isn't changing?
Line 419: Need a print statement at the end of this chunk, the last two columns don't show up
Line 437: change "sex" to "species of iris"
Line 477: Need to add grouping by year

Key points: Add "The lubridate package is useful for manipulating date data."

**Comment by maglet** [comment]
corrected in #51
