### ISSUE TITLE
ggplot2 episode suggestions

### ISSUE THREAD

**Issue by kathrynmichel** [uw-madison-comps/R-plant-lesson#47]
Line 260: The challenge 3 solution is not rendering.
Line 273: Why do we need to count the records in each group?
Line 324/325: Change "by the functional group of each individual measured" to "by the species within each functional group"
Line 325: Change "make counts" to "calculate the means"
Line 333: Change "sex" to "species" 

Challenge 4 is wonky...
Line 562: do you also need to specify height?
Key points: typo-"themes" not "themesthemes"

**Comment by maglet** [comment]
Fixed all but challenge 4 in #52
