### ISSUE TITLE
Clean up after merging pull request.

### ISSUE THREAD

**Issue by SteveGoldstein** [uw-madison-comps/R-plant-lesson#49]
After merging a pull request from, for example, my AdvancedLesson branch into the common gh-pages branch, I see a message like:

> You’re all set—the SteveGoldstein:AdvancedLesson branch can be safely deleted.

What happens when I click the "Delete Branch" button and what else do I need to do to clean up?

Let me guess at the answer:  

- "Delete Branch" does `git branch -d` on origin(https://github.com/SteveGoldstein/R-plant-lesson);

- I still need to do `git branch -d` in my local repo.

**Comment by maglet** [comment]
That's a pretty good description of what happens!
