### ISSUE TITLE
End of advanced lesson doesn't build. 

### ISSUE THREAD

**Issue by SteveGoldstein** [uw-madison-comps/R-plant-lesson#60]
When running `make serve` on 05-advanced-lesson.Rmd, it hits an error towards the end and doesn't render anything past the error:

> Quitting from lines 188-195 (_episodes_rmd/05-advanced-lesson.Rmd) 
> Error in get(as.character(call$data)) : object 'phys_data' not found
> Calls: source ... standardize -> .local -> standardize.default -> get
> 

I can't figure this out.  I think it has to do with scoping issues of chunks in the markdown files interacting with something into the `standardize()` call.

Here's what I observe:
- `phys_data` is accessed without error in the previous chunks.
- The code works for me when I execute it line-by-line in Rstudio.

**Comment by sstevens2** [comment]
This is really mystifying me.  Stripped down the script that makes this to the following script and called it from the command line and it seems to work fine.  We can always knit it using this script and then push that version instead of the served version?

```
require(knitr)

src_rmd <- "05-advanced-lesson.Rmd"
dest_md <- "../_episodes/05-advanced-lesson.md"

## knit the Rmd into markdown
knitr::knit(src_rmd, output = dest_md)
```

**Comment by maglet** [comment]
I fixed it by putting eval = FALSE on those code blocks.

**Comment by SteveGoldstein** [comment]
I've been working on paring this down to a minimal example that manifests the bug. (I think it's a bug in the arm package.)   @sstevens2 , when I have that example honed, to whom or how should I report it?
