### ISSUE TITLE
Inconsistency in naming physiological data

### ISSUE THREAD

**Issue by SteveGoldstein** [uw-madison-comps/R-plant-lesson#62]
In `03-dplyr.Rmd` and `04-visualization-ggplot2.Rmd`, the data frame with the phys data is called `plant_phys`;  in 05-advanced-lesson.Rmd, it's called `phys_data`.  Let change it to be the same in all the lessons.
@kimokeefe @maglet which is the better choice for the object name?

**Comment by kimokeefe** [comment]
Hm, I personally prefer phys_data because it's more specific that the object contains the data.

**Comment by maglet** [comment]
I can change it in my lessons, but it begs the question: should we change iris to iris_data?
