### ISSUE TITLE
dplyr lesson revision

### ISSUE THREAD

**Issue by jivarelao** [uw-madison-comps/R-plant-lesson#66]
Hello!
I proofread the dplyr lesson.
Here are my suggestions:

There is a "Enter **`dplyr`**"  on  line 48 that I believe it shouldn’t be there.

I think Challenge N3 can be rephrased with more instructions, something like:
Using the phys_data, create a new data frame that contains all data plus Month and Day in the 3th and 4th column.

For Challenge 5 I think the correct way to state it should be something like this:

How many individuals were measured for each specie in each Year?

Those are all my suggestions
It looks Great!!!

**Comment by SteveGoldstein** [comment]
I'll make these edits and then submit a pull request (later today).

**Comment by SteveGoldstein** [comment]
I incorporated these in PR #71
