### ISSUE TITLE
Add description of Kim's dataset

### ISSUE THREAD

**Issue by maglet** [uw-madison-comps/R-plant-lesson#67]
Because Steve doesn't use the plant physiology dataset, the data need to be described in the dplyr session

**Comment by SteveGoldstein** [comment]
Check with @kimokeefe and @kathrynmichel.  Kathryn said she's willing to introduce the phys_data (and scientific questions) at the beginning of the dplyr lesson.  And Kim can write a short paragraph to go into the narrative.

The pdf with a description of the columns of the data is in the zip file the learners download.

**Comment by kimokeefe** [comment]
I can do this. Is the dplyr lesson in the first or second workshop date?

**Comment by maglet** [comment]
second

**Comment by kimokeefe** [comment]
Okay cool. I'll get you something next week - I'm out of town again tomorrow and Friday.

**Comment by maglet** [comment]
@kimokeefe I added the table from the readme to the lesson in the latest PR, so the meanings of the variable names are in there.

**Comment by kimokeefe** [comment]
Great, thanks! That will be helpful. I also have a description of relevant variables for my lesson in the beginning of the lesson.

**Comment by maglet** [comment]
resolved by #82
