### ISSUE TITLE
Editing Kim's data: Dates

### ISSUE THREAD

**Issue by maglet** [uw-madison-comps/R-plant-lesson#7]
Hi all, 

Does anyone have any objections to changing the DOY column in Kim's data to Month, Day columns? It would make the time series of the ggplot2 lesson easier for me. 

Also if i do this, i might add some lubridate stuff to the dplyr lesson. Does that work for you?

**Comment by kimokeefe** [comment]
That sounds good to me - I think showing the students how to work with dates would be very helpful. Can you maybe leave the DOY column in as well? If I remember correctly, I think I used that in the analysis. If you think that would be too confusing to have both, it's not a big deal to take it out.

**Comment by maglet** [comment]
I Added a section on lubridate to the dplyr lesson.
