### ISSUE TITLE
Erin's edits for dplyr and ggplot

### ISSUE THREAD

**Issue by SteveGoldstein** [uw-madison-comps/R-plant-lesson#77]
**03-dplyr**

·         Objectives: Bullet point 6 is a vaguer version of 7. I would condense these by moving “split-apply-combine” into a parenthetical at the end of bullet 7 – or just omitting bullet 6 entirely but bolding/italicizing those three words in bullet 7 and leaving it otherwise as it is.

·         Data manipulation using dplyr and tidyr:

o   In the first sentence, we’re missing a comma after ‘read.’

·         What is dplyr?

o   Somewhere in this section or the next, I think you should say a few words more about the phys_data set – it felt a bit out-of-the-blue to encounter it here. I think it needs to be done before the first Challenge.

o   I notice that iris examples and phys_data examples are interleaved here. What goal are we trying to serve with that? – it’s a little confusing so I think we should make sure it’s filling a purpose.

·         Split-apply-combine data analysis and the summarize() function

o   Under Counting, the sentence starting “Previous example shows…” seems like a fragment (should it be “The previous example…”?) Similarly, it should be combinations of factors rather than combination.

·         Key points

o   The style for these should be unified across lessons. I propose beginning with a capital letter and ending with a period.

 

**04-visualization-ggplot2**

·         Plotting with ggplot2:

o   This style – bullet points above the code – is different enough from the other lessons that it’s a little jarring. Not sure there’s time to change it before the lesson, but unifying this is something to think about in future.

o   After “To add a geom to the plot use the + operator” – in that subsequent code chunk the + should be offset by a space (just for readability). There are a couple other instances of this so maybe a find/replace for “)+” is in order.

·         Building your plots iteratively:

o   The distinction between setting color inside and outside of aes() should be made a little more explicit, I think.

·         Key points

o   The style for these should be unified across lessons. I propose beginning with a capital letter and ending with a period.

o   In the first bullet, “require” should be “requires”

o   In the last bullet, it should read “…can be applied…”

**Comment by maglet** [comment]
I think these are addresssed in the most recent PR
