### ISSUE TITLE
Dplyr lesson suggestions 8-12-19

### ISSUE THREAD

**Issue by kathrynmichel** [uw-madison-comps/R-plant-lesson#9]
**When installing tidyverse** It can be useful to include "dependencies=T" to avoid installation problems.

**Under "What are dplyr and tidyr?":**  I think this statement is too advanced a concept to include in this lesson:
"The package dplyr provides easy tools for the most common data manipulation tasks. It is built to work directly with data frames, with many common tasks optimized by being written in a compiled language (C++). An additional feature is the ability to work directly with data stored in an external database. The benefits of doing this are that the data can be managed natively in a relational database, queries can be conducted on that database, and only the results of the query are returned.

This feature addresses a common problem with R in that all operations are conducted in-memory and thus the amount of data you can work with is limited by available memory. The database connections essentially remove that limitation in that you can connect to a database of many hundreds of GB, conduct queries on it directly, and pull back into R only what you need for analysis."

**Under the pipes challenge lesson** There is a typo in the plant_phys variable name (currently plant_phes)

**Under the mutate lesson** The statement "You can also create a second new column based on the first new column within the same call of mutate():" and following code doesn't make a new column based on the sepal ratio. 

**Under the split-apply-combine and summarize lesson** Should the print (n=15) statement be after a pipe to make it print? Also for the code: "indicating the minimum weight for each species for each sex", it finds the minimum by year and species not sex and species. The line: "If we want to sort the results by decreasing order of mean weight:" should read "decreasing order of minimum photosynthesis". The statement "From the table above, we may learn that, for instance, there are 75 observations of the albigula species that are not specified for its sex (i.e. NA)." does not apply to the described data. 

I will return to the spread/gather section later. 

**Under Exporting data** The code itself does not refer to the new folder, and I think the output folder needs to exist before you can refer to it in R. 

This is all looking wonderful, thank you for your hard work!!

**Comment by maglet** [comment]
Hi @kathrynmichel  FYI, we're removing gather and spread for time. Thanks for your comments!

If you find other things things that need to be addressed, please open a new issue
